### ISSUE TITLE
Crash when running

### ISSUE THREAD

**Issue by OOOOIIIO** [t-mw/gw2-arbitrage#5]
```
...
Loaded 26395 trading post prices
Loading detailed trading post listings
Fetching https://api.guildwars2.com/v2/commerce/listings?ids=4239,4243,8968,8995,9011,9061,9095,9130,9190,9250,10262,10264,10265,10282,10449,10691,10699,10702,10707,10709,10710,10722,10766,10767,10769,10786,10787,10791,10792,10796,10829,10830,10833,10834,10853,10854,10872,10874,10894,10961,11121,11126,11167,11247,11248,11295,11341,11389,11408,11409,11412,11431,11454,11455,11473,11477,11494,11508,11536,11538,11543,11573,11598,11603,11670,11834,11835,12007,12011,12013,12053,12055,12074,12076,12078,12097,12109,12128,12130,12134,12136,12138,12142,12143,12144,12153,12155,12156,12157,12158,12163,12166,12176,12178,12202,12229,12236,12253,12263,12271,12314,12324,12327,12347,12357,12394,12405,12438,12455,12459,12466,12467,12469,12472,12475,12507,12510,12513,12531,12532,12535,12544,12545,12557,12561,12590,12615,12634,12641,12642,12649,12662,12665,12670,12680,12806,12807,12808,12810,12811,12812,12813,12814,12816,12817,12818,12819,12823,12824,12825,12828,12829,12830,12831,12832,12833,12835,12836,12838,12841,12842,12844,12846,12847,12850,12851,12853,12854,12856,12859,12862,12865,12866,12868,12870,12871,12875,12878,12880,12883,12884,12886,12889,12890,12893,12894,12900,12901,12904,12910,12916,12917,12919,12920,12922,12925,12929,12930,12931,12935
Fetching https://api.guildwars2.com/v2/commerce/listings?ids=12936,12937,12943,12950,12951,12954,12955,12957,12960,12961,12967,12971,12973,12974,12975,12976,12977,12980,12981,12982,12984,12986,12988,12989,12990,12992,12993,12996,12999,13002,13005,13013,13014,13021,13022,13039,13040,13041,13042,13043,13044,13045,13046,13047,13048,13049,13050,13053,13055,13060,13061,13063,13064,13065,13068,13069,13070,13071,13072,13073,13074,13084,13085,13087,13088,13091,13093,13094,13095,13096,13098,13099,13100,13105,13106,13123,13124,13125,13126,13127,13128,13129,13130,13131,13132,13133,13134,13144,13145,13147,13148,13149,13150,13151,13152,13153,13154,13155,13156,13157,13158,13162,13163,13183,13184,13185,13186,13187,13188,13189,13190,13193,13194,13224,13225,13226,13227,13228,13229,13243,13245,13247,13251,13254,13255,13256,13259,13260,13261,13263,13265,13266,13278,13281,13283,13288,13290,13301,13302,13304,13307,13336,13342,13363,13425,13445,13520,13526,13527,13529,13531,13537,13538,13545,13546,13550,13552,13566,13571,13575,13719,13739,14051,14053,14056,14057,14061,14072,14079,14093,14096,14098,14102,14106,14122,14126,14184,14185,14188,14216,14517,14563,14566,14648,14765,14809,14819,14830,14845,14849,14870,14874,14949,14951,14981,14989,15314,15352,15423,15427
Fetching https://api.guildwars2.com/v2/commerce/listings?ids=15603,15607,15614,15615,15625,15626,15628,15631,15635,15666,15670,15688,15695,15696,15698,15713,15719,15730,15740,15751,15752,15761,15763,19679,19680,19681,19682,19683,19684,19685,19686,19687,19688,19697,19698,19699,19700,19701,19702,19703,19704,19709,19710,19711,19712,19713,19714,19718,19719,19720,19721,19722,19723,19724,19725,19726,19727,19728,19729,19730,19731,19732,19733,19734,19735,19736,19737,19738,19739,19740,19741,19742,19743,19744,19745,19746,19747,19748,19750,19757,19758,19761,19763,19767,19783,19789,19790,19791,19792,19793,19794,19795,19797,19799,19800,19802,19816,19869,19871,19880,19881,19882,19883,19884,19885,19886,19897,19899,19900,19901,19903,19919,19920,19924,19934,19935,19936,19937,19938,19939,19940,19941,19942,19943,19944,19945,19946,19947,19960,19962,19963,19964,19965,19966,19967,19968,19972,19975,24272,24273,24274,24275,24276,24277,24278,24279,24280,24282,24284,24285,24286,24287,24288,24290,24291,24292,24293,24294,24295,24296,24297,24298,24299,24302,24330,24341,24342,24343,24344,24346,24347,24348,24350,24351,24353,24354,24356,24357,24359,24360,24464,24465,24466,24467,24468,24469,24470,24471,24472,24474,24477,24478,24480,24483,24488,24494,24501,24503,24504,24506
Fetching https://api.guildwars2.com/v2/commerce/listings?ids=24507,24527,24534,24535,24748,24773,24872,24873,24875,24884,24898,24899,24900,24904,24906,24907,24908,24911,24912,24916,24917,29988,35524,36734,36756,36769,36773,37174,37178,37179,37897,37907,38139,38151,38166,38179,38264,43773,44941,45603,45616,45622,45629,45642,45731,45737,45759,45765,45798,45811,45911,45924,45995,46005,46008,46018,46180,46186,46262,46272,46298,46314,46327,46340,46353,46708,46713,46747,48609,48612,48614,49424,49425,49426,49427,49428,49429,49430,49431,49432,49433,49434,49435,49436,49437,49438,49439,49522,50082,62951,66637,66650,67528,67530,68063,70437,70647,70670,70714,70842,71049,71136,71225,71307,71336,71428,71583,71692,71702,71776,72048,72194,72349,72433,72549,72579,72752,72781,72807,72955,73034,73286,73471,74090,74202,74719,74852,74877,74982,75015,75181,75270,75570,75739,75857,76216,76297,76411,76478,76518,76614,76708,76839,77112,77256,82125,82582,82642,82678,82749,82796,82991,83103,83284,83757,84277,86601,91350,93397,93417,93440,93454,93596,93597
Loaded 742 detailed trading post listings
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\crafting.rs:271:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Application failed to run due to an issue in calculating crafting. Looking at the source, it looks like check at 269 is not covering all cases.

**Comment by OOOOIIIO** [comment]
Issue appears to be transient based on the state of the trade post API response, as it is working again. Sadly I do not have a print out of the entire API response to help debug.

**Comment by OOOOIIIO** [comment]
I got the error again and grabbed a print out of the API response:

```
Fetching https://api.guildwars2.com/v2/commerce/listings?ids=74202,74335,74719,74852,74877,74982,75015,75049,75123,75181,75226,75270,75570,75610,75654,75739,75857,76084,76216,76297,76361,76478,76518,76614,76708,76839,77064,77112,77256,82125,82171,82323,82582,82678,82749,82765,82796,83005,83103,83193,83284,83326,83342,83474,83616,83757,83926,84012,84191,84226,84277,84539,86601,91350,93351,93396,93397,93410,93417,93419,93435,93440,93454,93461,93481,93596,93597,93639
Loaded 846 detailed trading post listings
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\crafting.rs:271:22
```

[Response.txt](https://github.com/t-mw/gw2-arbitrage/files/6642326/Response.txt)

**Comment by t-mw** [comment]
Thanks for the detailed report, I think I see what's happening. I'll try and get a fix out soon!

**Comment by t-mw** [comment]
v0.5.0 should fix this, but it was a big change internally. I've tested it myself, but if you want to check that everything's working for you as well that'd be great.
